name: Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies @epsagon/web
        working-directory: ./packages/web
        run: npm install && npm run test && npm run build
      - name: Release @epsagon/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/web
        run: npm run semantic-release

      - name: Install dependencies @epsagon/react
        working-directory: ./packages/react
        run: npm install && npm run test && npm run build
      - name: Release @epsagon/react
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/react
        run: npm run semantic-release


